### ISSUE TITLE
how to set HADOOP_NAMENODE_HA

### ISSUE THREAD

**Issue by xurwxj** [smizy/docker-hadoop-base#1]
how to set HADOOP_NAMENODE_HA for enable ha?

**Comment by smizy** [comment]
@xurwxj set nn1,nn2. 
If you use command like "namenode=2  make_docker_compose_file.sh hdfs", it is automatically set.

**Comment by xurwxj** [comment]
ok, thks.
i've done through regenerate docker-compose.yml.
